[general]
import = ["~/.config/alacritty/carbonfox-vivid-oled.toml"]
ipc_socket = false

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 15.0

[font.normal]
family = "monospace"

[[hints.enabled]]
action = "Copy"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

# [[keyboard.bindings]]
# chars = "\u0017"
# key = "Back"
# mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control|Shift"

[terminal.shell]
program = "fish"

[window]
dynamic_padding = true
opacity = 0.80
startup_mode = "Maximized"

[window.padding]
x = 6
y = 6

[scrolling]
history = 10000

[cursor]
style.shape = "Beam"
