[colors]
background = '#181616'
foreground = '#c5c9c5'
selection-background = '#49473e'
selection-foreground = '#ddd8bb'
cursor = '#e6e0c2'
black = '#181616'
red = '#c4746e'
green = '#8a9a7b'
yellow = '#c4b28a'
blue = '#8ba4b0'
magenta = '#c292a5'
cyan = '#8ea4a2'
white = '#c8c093'
light-black = '#a6a69c'
light-red = '#e46876'
light-green = '#87a987'
light-yellow = '#e6c384'
light-blue = '#7fb4ca'
light-magenta = '#938aa9'
light-cyan = '#7aa89f'
light-white = '#c5c9c5'
