[colors]
background = '#000000'
foreground = '#ffffff'
selection-background = '#2d4f67'
selection-foreground = '#bcbcaf'
cursor = '#bcbcaf'
black = '#322a2c'
red = '#d04363'
green = '#9b9329'
yellow = '#bf7a29'
blue = '#6a8c8c'
magenta = '#856774'
cyan = '#757978'
white = '#bcbcaf'
light-black = '#46423b'
light-red = '#ae837a'
light-green = '#b4aa30'
light-yellow = '#c7a551'
light-blue = '#74999a'
light-magenta = '#9c818e'
light-cyan = '#9fa590'
light-white = '#c1c4bc'
